version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15
    container_name: poker-db
    environment:
      POSTGRES_DB: poker_db
      POSTGRES_USER: poker_user
      POSTGRES_PASSWORD: poker_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poker_user -d poker_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - poker-network

  # Backend API
  backend:
    build: ./backend
    container_name: poker-backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=poker_db
      - DB_USER=poker_user
      - DB_PASSWORD=poker_password
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - poker-network

  # Frontend
  frontend:
    build: ./frontend
    container_name: poker-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - poker-network

volumes:
  postgres_data:

networks:
  poker-network:
    driver: bridge