services:
  # PostgreSQL Database
  database:
    image: postgres:15
    container_name: poker-db
    environment:
      POSTGRES_DB: poker_db
      POSTGRES_USER: poker_user
      POSTGRES_PASSWORD: poker_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poker_user -d poker_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: ./backend
    container_name: poker-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://poker_user:poker_password@database:5432/poker_game
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build: ./frontend
    container_name: poker-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data: